/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';
import {
  Project,
} from './bestofjs';

export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface AppSearch {}
  interface ProjectAvatar {
    'project': Project;
    'size': number;
  }
  interface ProjectTable {
    'projects': Array<Project>;
  }
  interface SearchBox {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSearchElement extends Components.AppSearch, HTMLStencilElement {}
  var HTMLAppSearchElement: {
    prototype: HTMLAppSearchElement;
    new (): HTMLAppSearchElement;
  };

  interface HTMLProjectAvatarElement extends Components.ProjectAvatar, HTMLStencilElement {}
  var HTMLProjectAvatarElement: {
    prototype: HTMLProjectAvatarElement;
    new (): HTMLProjectAvatarElement;
  };

  interface HTMLProjectTableElement extends Components.ProjectTable, HTMLStencilElement {}
  var HTMLProjectTableElement: {
    prototype: HTMLProjectTableElement;
    new (): HTMLProjectTableElement;
  };

  interface HTMLSearchBoxElement extends Components.SearchBox, HTMLStencilElement {}
  var HTMLSearchBoxElement: {
    prototype: HTMLSearchBoxElement;
    new (): HTMLSearchBoxElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-search': HTMLAppSearchElement;
    'project-avatar': HTMLProjectAvatarElement;
    'project-table': HTMLProjectTableElement;
    'search-box': HTMLSearchBoxElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface AppSearch {}
  interface ProjectAvatar {
    'project'?: Project;
    'size'?: number;
  }
  interface ProjectTable {
    'projects'?: Array<Project>;
  }
  interface SearchBox {
    'onQueryChange'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-search': AppSearch;
    'project-avatar': ProjectAvatar;
    'project-table': ProjectTable;
    'search-box': SearchBox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-search': LocalJSX.AppSearch & JSXBase.HTMLAttributes<HTMLAppSearchElement>;
      'project-avatar': LocalJSX.ProjectAvatar & JSXBase.HTMLAttributes<HTMLProjectAvatarElement>;
      'project-table': LocalJSX.ProjectTable & JSXBase.HTMLAttributes<HTMLProjectTableElement>;
      'search-box': LocalJSX.SearchBox & JSXBase.HTMLAttributes<HTMLSearchBoxElement>;
    }
  }
}


